apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repository-tool.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "repository-tool.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ required (printf "secrets.%s must be set" $key) $value | quote }}
  {{- end }}
