apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repository-tool.fullname" . }}-github-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "repository-tool.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.github.token | quote }}
