package templates

import (
	"strings"
	"testing"
)

var testData = RepoData{
	Name:        "test-service",
	Description: "A test microservice",
	Owner:       "testuser",
	Year:        2026,
}

func TestReadme(t *testing.T) {
	result := Readme(testData)

	checks := []string{
		"# test-service",
		"A test microservice",
		"go run main.go",
		"docker build",
		"curl http://localhost:8080",
	}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf("README missing %q", c)
		}
	}
}

func TestReadme_EmptyDescription(t *testing.T) {
	data := RepoData{Name: "test", Owner: "user", Year: 2026}
	result := Readme(data)

	if !strings.Contains(result, "generated by") {
		t.Error("expected default description for empty input")
	}
}

func TestGitignore(t *testing.T) {
	result := Gitignore()

	checks := []string{".exe", ".env", ".DS_Store", "go.work", "/bin/"}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf(".gitignore missing %q", c)
		}
	}
}

func TestLicense(t *testing.T) {
	result := License(testData)

	if !strings.Contains(result, "MIT License") {
		t.Error("expected MIT License header")
	}
	if !strings.Contains(result, "2026") {
		t.Error("expected year 2026")
	}
	if !strings.Contains(result, "testuser") {
		t.Error("expected owner name")
	}
}

func TestGoMod(t *testing.T) {
	result := GoMod(testData)

	if !strings.Contains(result, "module github.com/testuser/test-service") {
		t.Errorf("unexpected go.mod content: %s", result)
	}
	if !strings.Contains(result, "go 1.26") {
		t.Error("expected go 1.26 directive")
	}
}

func TestMicroservice(t *testing.T) {
	result := Microservice(testData)

	checks := []string{
		"package main",
		"net/http",
		"handleRoot",
		"handleHealth",
		`"test-service"`,
		"Hello from test-service",
		"8080",
	}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf("microservice missing %q", c)
		}
	}
}

func TestServiceDockerfile(t *testing.T) {
	result := ServiceDockerfile()

	checks := []string{
		"FROM golang:1.26-alpine",
		"FROM alpine:3.21",
		"CGO_ENABLED=0",
		"EXPOSE 8080",
	}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf("Dockerfile missing %q", c)
		}
	}
}

func TestCIWorkflow(t *testing.T) {
	result := CIWorkflow()

	checks := []string{
		"name: CI",
		"pull_request",
		"actions/checkout@v4",
		"actions/setup-go@v5",
		"golangci-lint-action@v6",
		`go-version: "1.26"`,
	}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf("CI workflow missing %q", c)
		}
	}
}
